### ISSUE TITLE
Files removed from cache automatically 

### ISSUE THREAD

**Issue by fishcharlie** [cryptomator/ios#104]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

It seems like recently cached files were removed from the cache. However in the Files app thumbnails still show up, but it has a download icon. After redownloading it the cache size increases, which shows that it wasn’t cached.

### System Setup

- iOS: 15.2 (19C5036e)
- Cryptomator: 2.0.0 (609)

### Steps to Reproduce

Unsure. Seems to be automatic.

### Expected Behavior

Cached files to only be removed from cache when clear cache button pressed.

### Actual Behavior

Files removed from cache without any user interaction.

### Reproducibility

Intermittent

**Comment by phil1995** [comment]
Thanks for reporting the issue.
The behavior you describe was caused by the update to beta8. This is because in beta8 the "FileProviderExtension database" is deleted due to changes in the schema. In this database we also store the information about the cached files. Deleting the database when the schema changes is done exclusively during the pre-release beta phase, later we migrate the existing database. We know that sometimes this is a bit unexpected and can cause annoyances (in previous beta versions, vaults had to be added again in the main app because we deleted the "Main App database"), but otherwise we would have a lot of migration code written exclusively for the pre-release betas in our codebase.

The behavior that the thumbnails were still visible is to be expected, this also happens when the entire cache is manually cleared (see #89 for more details).

If the behavior you describe occurs again, feel free to reopen the issue.
