### ISSUE TITLE
Allow HTTP for WebDAV Connection

### ISSUE THREAD

**Issue by NN708** [cryptomator/ios#109]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Unable to use WebDAV over HTTP

### System Setup

- iOS: 15.1
- Cryptomator: 2.0.0 (609)

### Cloud Type

WebDAV

### Steps to Reproduce

Connect to a WebDAV service over HTTP.

### Expected Behavior

Connected to the WebDAV service without TLS.

### Actual Behavior

Error occurred: CryptomatorCloudAccess-Core.TLSCertificateValidatorError error 0.

### Reproducibility

Always

**Comment by tobihagemann** [comment]
It's not actually a "bug" (you could argue that it's a security feature) but I'll change this issue it to an enhancement since we've already been through this with the old app. The following has to be done:

1. Add this to the `Info.plist` (and check if this is also needed for the app extensions):

```xml
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```

2. Add the following confirmation dialog if you try to add a WebDAV connection with HTTP:

```
Title: "Use HTTPS?"
Message: "The usage of HTTP is insecure. We recommend to use HTTPS instead. If you know the risks, you can continue with HTTP."
Default Button: "Change to HTTPS"
Cancel Button: "Keep HTTP"
```

**Comment by NN708** [comment]
Thanks for your response! I’m using WebDAV in my local network, so I think it’s secure enough to just use HTTP. The confirmation dialog is a great idea.
