### ISSUE TITLE
Automatic Photo Upload: Reactively sync all photos from iPhone to a vault

### ISSUE THREAD

**Issue by qishen** [cryptomator/ios#114]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Sync all photos from iPhone local storage to a vault

### Motivation

I expect Cryptomator to sync all data including photos to an encrypted vault since my motivation is to use Cryptomator to get rid of the iCloud but still be able to back up all photos in a secret place on the cloud. I'm not familiar with ios development but I realize Apple may have strict rules for apps to access user photos so it could be an impossible feature to add when an app behaves like malware to read photos in the background. Any thoughts and workarounds?

**Comment by tobihagemann** [comment]
We haven't figured this out yet so I'll keep this open as a feature request. Since Cryptomator is now part of the Files app, we would've hoped that we could make use of native iOS features, like Shortcuts.

In any case, #73 is probably a blocker for this feature.

**Comment by anykeymeister** [comment]
>In any case, #73 is probably a blocker for this feature.

Hello! Seems like #73 case solved in v2.1. Any news about photo upload?

**Comment by tobihagemann** [comment]
Yes, #73 was a key feature that is needed for "Automatic Photo Upload". We've already done some experiments and we're confident that this feature can be achieved via Shortcuts. However, it doesn't work out of the box because there is no built-in shortcut for saving something automatically in the Files app (it defaults to iCloud Drive, which is not, what we need). There is a shortcut for saving something via a document picker (so that we could select a Cryptomator vault) but that isn't really automatic. :smile: Therefore, we have to add a custom shortcut, which will be part of #56.

**Comment by Dex321x** [comment]
Looking forward to this feature, and I'm happy you are working on it. Can you give an approximate timeline for this feature?

**Comment by tobihagemann** [comment]
We are currently planning it for the next minor release 2.3.0.

**Comment by DaveFlowberries** [comment]
> We are currently planning it for the next minor release 2.3.0.

Awesome, I remember reading somewhere that the issue was leaving the vault open all the time to make it work? If so, I found something that might help: (sorry I am not a coder so not sure if this is relevant, but another user had success with it for auto photo album uploads to cryptomator)

https://old.reddit.com/r/shortcuts/comments/9p2vix/cryptokit_a_cryptography_shortcut/

CryptoKit

This shortcut is used to store sensitive data like passwords encrypted in a shortcut. If you share a shortcut but forgot to remove a password, you don't have to worry about that anymore. Or if you share your device, other people can't read it in plain text if they find it by coincidence.

It uses the Stanford Javascript Crypto Library, which used AES-CBC-256 as encryption method.

It supports two different modes. Either using a master password (default) or using a generated key. Each has one advantage over the other:
Master password mode

    + It's more secure, as no one who has access to your shortcuts can decrypt your passwords
        - You have to enter it every time this shortcut is run

Generated key mode

    + You don't have to enter a password every time -> faster shortcut execution
    - Less secure as everyone who has access to your shortcuts can decrypt your passwords

**Comment by ueismann** [comment]
I used shortcut and automation as suggested, and have the shortcut executed every night. However most of the pics do not get uploaded, although I limited the number of pics to significantly less than 100 (default was 120 from the shortcut). Actual daily number of pics is on the order of 10, and only a fraction gets uploaded. Of course, manual uploading of the pics with the one-way-street-sign is possible, but quite tedious and not in the true sense of cloud integration of photos or automation in general.

config:
iphone 12
iOS 15.6.1
cryptomator 2.4.1(997)
nextcloud via WebDAV from [hosting.de](http://hosting.de/)

**Comment by anykeymeister** [comment]
Hello! Seems like feature works for current release.
So what about auto photo sync to vault?

**Comment by tobihagemann** [comment]
Check out our Shortcuts guide on how to set up "Automatic Photo Upload": https://docs.cryptomator.org/en/latest/ios/shortcuts-guide/

**Comment by matt22207** [comment]
@tobihagemann ,

Wondering if this feature request could be reconsidered as a proper feature instead of the Shortcut method? It seems there are a number of issues with the current Shortcuts method (that may be outside of your control) :

- Videos no longer sync: https://github.com/cryptomator/ios/issues/447
- Live Images don't sync: https://github.com/cryptomator/ios/issues/210
- Additionally, I found that individual photos synced via the Shortcut (with Vault on Dropbox as backend) are given the file timestamp of the sync, rather setting the new file with a timestamp of when the photo was taken. Not super critical, but annoying since we can't sort the resulting photo folders reliably by date. (I can open a new bug report if requested, but I'm currently assuming this isn't possible with the Shortcut method). Note, the original photo date is however retained in the photo metadata, so maybe there's a utility on a desktop computer that can rewrite these.
  - For reference in case anyone else stumbles upon this, I was able to get at least something working on my desktop after syncing to rewrite the file modification date based on the EXIF data : `exiftool "-FileModifyDate<CreateDate" *`
- Probably some other issues buried in various other reports: https://github.com/cryptomator/ios/issues?q=is%3Aissue%20photos

I do appreciate that building this functionality within the Cryptomator app would be a large undertaking and is generally beyond the scope of an app mainly focused on providing encrypted storage, but hoping it could be reconsidered given these issues. I was also hoping maybe using a third party app with Cryptomator as the storage location might be feasible, but seems not ( via: #341 / #48 ), unless anything has changed in recent iOS versions.

Thanks!
