### ISSUE TITLE
"Outside" changes to masterkey and vault config are not considered

### ISSUE THREAD

**Issue by nassim-2000** [cryptomator/ios#142]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

I created vault on local storage on my Iphone and just for testing, i choose to delete masterkey.cryptomator file but in iPhone Files App, i can access and decrypt files which contains my vault without the key file.

thanks for your support ! :)

### What software is involved?

- Operating System: IOS 15.1.1
- Cryptomator: 2.0.4
- use Cryptomator on File App of IOS

### Volume Type

FUSE

### Steps to Reproduce

1. 
Create a vault 

2. 
Delete the file key « masterkey.cryptomator » in the vault

3. 
decrypt with face id or password the vault (you can access it without the key file)

### Expected Behavior

an error because the file master key is not found

### Actual Behavior

i can access to files, the file "masterkey.cryptomator" is detect as not found only when i remove the vault and try to add it a new time on app

### Reproducibility

Always

**Comment by tobihagemann** [comment]
We are aware of this problem and will work on it. But it will not be part of the next update. Probably in the one after that.

**Comment by nassim-2000** [comment]
Okay, however, the fact that one can decrypt without the files that are responsible for the decryption key poses a lot of security questions.  Files remain cached?

**Comment by tobihagemann** [comment]
Yes, the encrypted masterkey file and the vault config file are cached. But these files are the same ones in the cloud so you cannot just use them for decryption. You still need the password, which is not cached (except you're using Face ID / Touch ID, which stores the password inside the keychain for biometric authentication).

We understand that this could cause undesirable effects, that's why we're definitely fixing that. But I can't think of a security issue in that regard. Even if you'd replace the whole vault with a different one "from the outside", the encrypted data will then be stored with a different masterkey, which would be unreadable for other clients. It's undesirable but doesn't leak anything.
