### ISSUE TITLE
Encrypted files visible in Siri Search

### ISSUE THREAD

**Issue by plasticrhinox** [cryptomator/ios#153]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

On iOS you can view the thumbnails of encrypted files if you search for the file names in Siri search.

### What software is involved?

- Operating System: iOS 15.2
- Cryptomator: 2.0.4
- Hardware: iPhone XS Max

### Steps to Reproduce

1. Unlock your vault and view images through the Files app (remember the file names of the viewed files).
2. Close the Files app and lock your vault using the Cryptomator app.
3. At the home screen swipe down to reveal the Siri Search field.
4. In the search field type the file name for one of the files you viewed in Step 1.

### Expected Behavior

Files and associated thumbnails should not appear in the search results when the vault is locked.

### Actual Behavior

1. The file will appear in the Files section of the search results.
2. You cannot open the file from here, however if you click the **Search in App** link next to the Files header the Files app will open and present the thumbnails of the images.
3. The images cannot be opened from here but the thumbnails will be clearly visible.

### Reproducibility

Always

**Comment by phil1995** [comment]
It seems that files opened by the user in the Files app are added to the working set by iOS itself. And since according to the [documentation](https://developer.apple.com/documentation/fileprovider/content_and_change_tracking/defining_your_file_provider_s_content#2897861) "the documents in the working set are indexed in the device's Spotlight database", these files will show up in the search on the iOS device even if the vault is locked.
We can prevent this behavior by actively triggering an enumeration on the working set ourselves and deliberately letting it fail using `NSFileProviderErrorSyncAnchorExpired`, which will remove all cached data according to the documentation in the [SDK](https://github.com/xybp888/iOS-SDKs/blob/a110a31ce82e42621b3e7ba31bd6563c02d2631a/iPhoneOS14.5.sdk/System/Library/Frameworks/FileProvider.framework/Headers/NSFileProviderEnumerating.h#L89-L94) for `finishEnumeratingWithError(_:)`. Note this behavior is not found in the [official documentation](https://developer.apple.com/documentation/fileprovider/nsfileproviderenumerationobserver/2879612-finishenumeratingwitherror) for `finishEnumeratingWithError(_:)`, but it definitely works and removes the indexed items from the Spotlight database again.
