### ISSUE TITLE
High consumption of battery due to background activities

### ISSUE THREAD

**Issue by blu-e-man** [cryptomator/ios#206]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

High consumption of battery due to background activities

### System Setup

- iOS: 15.4.1
- Cryptomator: 2.2.3 (917)
- iPhone 12 Pro Max

### Cloud Type

WebDAV

### Steps to Reproduce

It is a permanent problem that cannot be reproduced by a specific behavior. 

### Expected Behavior

No background activity from 60-80% / hour according to iOS battery settings. 

### Actual Behavior

Background activity of Cryptomator is about 60 - 80 % / hour.
This makes it necessary to charge the iPhone several times a day. 

### Reproducibility

Always

**Comment by tobihagemann** [comment]
Thank you for your report! This is actually not the very first report about this but it's good that we an issue on GitHub now. We got various reports via our community, via email, and via user reviews in the App Store.

But we actually can't make any sense of it. Cryptomator shouldn't do anything in the background. Since it's a File Provider extension, it just "reacts" to calls from the Files app.

I'm wondering now about the following: Background activity is one thing but does it actually _consume_ a lot of battery? Could you please switch to "Show Battery Usage" inside the "Battery" settings and check if Cryptomator is actually using a lot?

**Comment by blu-e-man** [comment]
> I'm wondering now about the following: Background activity is one thing but does it actually _consume_ a lot of battery? Could you please switch to "Show Battery Usage" inside the "Battery" settings and check if Cryptomator is actually using a lot?

I just had a look for the night between 04:00 and 05:00.
Battery usage per app: Cryptomator 73%.
