### ISSUE TITLE
Video can still be played after vault is locked. Thumbnails can still be viewed as well.

### ISSUE THREAD

**Issue by DaveFlowberries** [cryptomator/ios#217]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Video can still be played after vault is locked. Thumbnails can still be viewed as well.

### System Setup

- iOS: 15.4.1
- Cryptomator: 2.2.4 (9.2.7)

### Cloud Type

Didn't test. Files are stored locally on the iPhone storage. No cloud use.

### Steps to Reproduce

1. Open vault and play video.
2. Lock vault in Cryptomator
3. Open App Switcher (Swipe up from the bottom of the screen, then pause in the center of the screen) and you will see the video is still there and can be played without issue when the vault is supposedly locked. In addition, the thumbnails in file view can still be seen.

### Expected Behavior

Video and thumbnails should have been inaccessible.  

### Actual Behavior

Video plays when vault says "locked" and video/photo thumbnails can still be viewed in the App Switcher in the files view when locked.

### Reproducibility

Always

### Anything else?

Only workaround is to manually close them, but it begs the question, is the encryption even working if the video can still be played? 

"Clear Cache" option within Cryptomator settings does not remedy the issue.

**Comment by phil1995** [comment]
Hello @DaveFlowberries,

the behavior you describe is indeed the expected one. This is because the FileProvider API expects to make a file available locally in the unencrypted state as soon as the user requests it (for example, by opening the video). This is also in line with our [security target](https://docs.cryptomator.org/en/latest/security/security-target/) - of course, we still strive to protect users' files locally as much as possible.
If a vault is locked, we deny new file accesses, but have no influence on possibly still existing ones. Therefore, it is possible that an already opened file (in your case the video file) is still available in the video player even if the vault is locked.

> "Clear Cache" option within Cryptomator settings does not remedy the issue.

That is indeed an interesting observation! That would mean that the video player itself is caching the file in some way - did you use the normal iOS video player?

**Comment by DaveFlowberries** [comment]
> That is indeed an interesting observation! That would mean that the video player itself is caching the file in some way - did you use the normal iOS video player?

Yes, the normal player.

BTW, I noticed that VLC player with passcode enabled does not exhibit this kind of behavior. Is there a way to change the default video player in cryptomator?
