### ISSUE TITLE
Force FaceID in files app

### ISSUE THREAD

**Issue by micha-09** [cryptomator/ios#225]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Force unlock via FaceID in files app as standard

### Motivation

When opening a Cryptomator vault in the Apple Files app, the Cryptomator interface opens and requests that the folder be unlocked.
To be able to use FaceID for unlocking I have to press the button "Unlock via FaceID" so that the iPhone unlocks the vault via FaceID.
If FaceID is enabled for this Cryptomator vault, it would be much faster and more convenient if FaceID is tried directly by default when opening the files, without having to select it first.

![IMG_CF4CB096A94D-1](https://user-images.githubusercontent.com/803483/171016407-83ad4dd1-589f-4a2d-9e70-f50fe724b34f.jpeg)

**Comment by tobihagemann** [comment]
Thank you for your feature request! Just wanted to let you know that we were actually considering this right from the beginning but encountered an upstream bug that was also mentioned in #72. We just got a notification from Apple that this upstream bug is probably fixed in iOS 16 but we haven't confirmed it yet.

Regardless of the upstream bug, we could implement a "workaround" like this:

1. Unlock vault instantly via Face ID / Touch ID.
2. If it fails, step 1 will be skipped and the unlock screen will be shown.

**Comment by micha-09** [comment]
It would be nice, if you implement this workaround :) Are there an plans to do this?
