### ISSUE TITLE
Unable to rename vault

### ISSUE THREAD

**Issue by th3boz** [cryptomator/ios#374]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

The vault name is always “/“ and it cannot be changed

### What software is involved?

- Operating System: iOS
- Cryptomator: lastest version

### Volume Type

WebDAV (HTTP Address)

### Steps to Reproduce

When you add an exinting vault via wedbav connection on iOS, once you have selected it, Cryptomator assign the name “/“ to the vault and ask for the password. Once you have entered the password it adds correctly the vault in the application, but its name will be “/“ and you cannot change it.

### Expected Behavior

Have the possibility to rename the vault once added.

### Actual Behavior

You cannot rename the vault.

### Reproducibility

Always

**Comment by tobihagemann** [comment]
If you add the WebDAV connection, please make sure that the URL doesn't match the exact root directory of the vault. Otherwise, Cryptomator doesn't have a chance to be able to rename a vault, because it's the root directory (and root directories don't have "names"). That's why this is not really a bug that can be fixed. You have to correct your URL to the actual root directory of your WebDAV storage or to some parent of the vault.
