### ISSUE TITLE
Possible BUG on IOS

### ISSUE THREAD

**Issue by kmenge0707** [cryptomator/ios#380]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Cannot connect from IOS via Cryptomator to Strato Hidrive

### What software is involved?

- Operating System: IOS 17.6.1
- Cryptomator: Latest IOS version
- …

### Volume Type

None

### Steps to Reproduce

1. Open Cryptomator app
2. Click „Open in Files“
3. Cannot open files, see attached screenshot

### Expected Behavior

Want to open files

### Actual Behavior

error message comes up, see attached screenshot

### Reproducibility

Always

### Anything else?

![IMG_0916](https://github.com/user-attachments/assets/99ac2428-124e-46c1-913c-e39157ed7b79)

**Comment by iammajid** [comment]
@kmenge0707 

Thank you for your bug report.

It appears that your device cannot connect to your Strato HiDrive account. The error message suggests there might be an issue with the server or your network connection.

Possible Solution:

- Reconnect to HiDrive:
  - Please try removing the connection to your Strato HiDrive account within the Cryptomator app.
  - Then, add the HiDrive account again and attempt to access your vault.

This process can help refresh the connection and resolve any authentication issues.

Additional Steps:

- If the problem persists after reconnecting, please enable Debug Mode in the app settings (if you haven't already), reproduce the error, and then send us the log file via email(support@cryptomator.org). This will help us understand what's happening in the background.

Note:

- The issue may not necessarily be related to Cryptomator; it could also be due to network connection problems or issues on the HiDrive service side.

Please let us know if reconnecting resolves the issue or if you need further assistance.
