### ISSUE TITLE
Make Files integration optional

### ISSUE THREAD

**Issue by olfway** [cryptomator/ios#57]
### Summary

Although Files integration was one of the most requested feature it unfortunately not fits all usage scenarios

### Motivation

For some vaults I would prefer to not have Files integration and open them via in-app (pin or password protected) browser.
Some files or documents shouldn't be accessible even on unlocked phone.

I understand that if I give my phone and pin to someone else then I shouldn't trust it anymore and that I shouldn't open cryptomator on it either.
But I guess more often scenario is then you temporary gives your unlocked phone to a friend or family member to see a photo or play a music but I don't want to show all my private documents in File app to them

### Considered Alternatives

I tried to look for alternatives but unfortunately I didn't found any. Looks like pre-Files version will be deprecated.
Please, suggest an alternative if you know one

**Comment by phil1995** [comment]
We are already working on unlocking a vault directly in the Files app. This way a vault does not have to be permanently unlocked. I think this should fix the problem?

**Comment by olfway** [comment]
Not exactly, I prefer some vaults to be accessible only in cryptomator app without any ios integrations.
Ie Siri, Files app, system-wide search, recently opened files, cached thumbnails, etc.

I would prefer cryptomator to be a standalone secure container for the documents that needs to be secure.

**Comment by tobihagemann** [comment]
To be completely honest and it might not surprise you, this doesn't exactly fit on our roadmap for this app. The new app has been written from the ground up to be fully integrated into the Files app so that we don't have to maintain "our own" file browser anymore.

Our goal still remains that Cryptomator will be a protected space, even inside the Files app. This might not be the case in the current beta yet but that's what we're striving for. In the end, it's like using Finder or Windows Explorer on Desktop. And yes, phones are a bit different than computers but we'll add features like auto-lock functionality to prevent access if you e.g. give your phone temporarily away.

**Comment by phil1995** [comment]
By the way, this is exactly the reason why the system-wide search and recently opened files are not supported.

**Comment by olfway** [comment]
> it's like using Finder or Windows Explorer on Desktop
You know, for some documents I would prefer to use in-app browser even on desktop, without virtual fuse drives
It will also helps with ransomware and other non-cryptomator specific attacks
