### ISSUE TITLE
Contain Vault within Folder in Files app

### ISSUE THREAD

**Issue by fishcharlie** [cryptomator/ios#92]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Currently within the Files app when tapping Cryptomator it takes you directly into the vaults contents itself. It would be a good idea to have the contents be contained within a folder with the vaults name.

### Motivation

Easier for the user to understand and better UX.

**Comment by Taxyovio** [comment]
I don’t think @phil1995 understood the problem correctly.

When you have multiple vaults, there’re still no folders. Those vaults are mounted as distinct locations on the sidebar. The sidebar quickly gets dominated with a bunch of separate Cryptomator locations when there’re many vaults. I’d personally preferred vaults are mounted in a single location as different folders.

**Comment by phil1995** [comment]
Hi @Taxyovio,
I think I understood fishcharlie's problem correctly, as he was only concerned with differentiating the vaults within the Files app.  The scenario you described with multiple vaults within a single `FileProviderDomain` (the location in the sidebar) leads to the restriction that vaults can no longer be unlocked individually in the Files app, since we can only lock an entire `FileProviderDomain` (we need to lock / mark a FileProviderDomain as not authenticated in order to trigger the modal, which lets you unlock your vault inside the files app). Thus, with the approach you described, it is not possible to unlock the vaults individually in the Files app, since all vaults are located in subfolders in the same (locked) FileProviderDomain.
It would be technically feasible to unlock the vaults only in the main app and display each locked vault as an empty folder in the Files app. However, in my opinion, this leads to a worse user experience, since it is unclear whether the vault is locked or not and, in addition, the user must leave the Files app every time he wants to unlock his vault.
